config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: "users/registrations", sessions: "users/sessions" }
  root 'welcome#index'
  get '/users/:user_id/user_albums/data' => "user_albums#data"

  authenticate :user do
    resources :songs
    resources :albums
    resources :artists
    resources :user_albums
    get '/search' =>'search#index'
  end
end

#                   Prefix Verb   URI Pattern                                Controller#Action
#         new_user_session GET    /users/sign_in(.:format)                   users/sessions#new
#             user_session POST   /users/sign_in(.:format)                   users/sessions#create
#     destroy_user_session DELETE /users/sign_out(.:format)                  users/sessions#destroy
#            user_password POST   /users/password(.:format)                  devise/passwords#create
#        new_user_password GET    /users/password/new(.:format)              devise/passwords#new
#       edit_user_password GET    /users/password/edit(.:format)             devise/passwords#edit
#                          PATCH  /users/password(.:format)                  devise/passwords#update
#                          PUT    /users/password(.:format)                  devise/passwords#update
# cancel_user_registration GET    /users/cancel(.:format)                    users/registrations#cancel
#        user_registration POST   /users(.:format)                           users/registrations#create
#    new_user_registration GET    /users/sign_up(.:format)                   users/registrations#new
#   edit_user_registration GET    /users/edit(.:format)                      users/registrations#edit
#                          PATCH  /users(.:format)                           users/registrations#update
#                          PUT    /users(.:format)                           users/registrations#update
#                          DELETE /users(.:format)                           users/registrations#destroy
#                     root GET    /                                          welcome#index
#                          GET    /users/:user_id/user_albums/data(.:format) user_albums#data
#                    songs GET    /songs(.:format)                           songs#index
#                          POST   /songs(.:format)                           songs#create
#                 new_song GET    /songs/new(.:format)                       songs#new
#                edit_song GET    /songs/:id/edit(.:format)                  songs#edit
#                     song GET    /songs/:id(.:format)                       songs#show
#                          PATCH  /songs/:id(.:format)                       songs#update
#                          PUT    /songs/:id(.:format)                       songs#update
#                          DELETE /songs/:id(.:format)                       songs#destroy
#                   albums GET    /albums(.:format)                          albums#index
#                          POST   /albums(.:format)                          albums#create
#                new_album GET    /albums/new(.:format)                      albums#new
#               edit_album GET    /albums/:id/edit(.:format)                 albums#edit
#                    album GET    /albums/:id(.:format)                      albums#show
#                          PATCH  /albums/:id(.:format)                      albums#update
#                          PUT    /albums/:id(.:format)                      albums#update
#                          DELETE /albums/:id(.:format)                      albums#destroy
#                  artists GET    /artists(.:format)                         artists#index
#                          POST   /artists(.:format)                         artists#create
#               new_artist GET    /artists/new(.:format)                     artists#new
#              edit_artist GET    /artists/:id/edit(.:format)                artists#edit
#                   artist GET    /artists/:id(.:format)                     artists#show
#                          PATCH  /artists/:id(.:format)                     artists#update
#                          PUT    /artists/:id(.:format)                     artists#update
#                          DELETE /artists/:id(.:format)                     artists#destroy
#              user_albums GET    /user_albums(.:format)                     user_albums#index
#                          POST   /user_albums(.:format)                     user_albums#create
#           new_user_album GET    /user_albums/new(.:format)                 user_albums#new
#          edit_user_album GET    /user_albums/:id/edit(.:format)            user_albums#edit
#               user_album GET    /user_albums/:id(.:format)                 user_albums#show
#                          PATCH  /user_albums/:id(.:format)                 user_albums#update
#                          PUT    /user_albums/:id(.:format)                 user_albums#update
#                          DELETE /user_albums/:id(.:format)                 user_albums#destroy

app/models/artist.rb
class Artist < ActiveRecord::Base
	has_many :albums
	has_many :songs, through: :albums
	include PgSearch
  pg_search_scope :search_by_name, 
                  :against => [:artist_name],
                  :using => {
                    :tsearch => {:prefix => true}
                  }

	private
	def self.search(query) 
    	Artist.search_by_name(query)
  	end
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  skip_before_filter :verify_authenticity_token
  before_action :set_artist, only: [:show, :edit, :update, :destroy]

  # GET /artists
  # GET /artists.json
  def index
    @artists = Artist.all
  end

  # GET /artists/1
  # GET /artists/1.json
  def show
    @artist = Artist.find(params[:id])
  end

  # GET /artists/new
  def new
    @artist = Artist.new
  end

  # GET /artists/1/edit
  def edit
  end

  # POST /artists
  # POST /artists.json
  def create
    @artist = Artist.new(artist_params)
    # binding.pry
    respond_to do |format|
      if @artist.save
        format.html { redirect_to @artist, notice: 'Artist was successfully created.' }
        format.json { render :show, status: :created, location: @artist }
      else
        format.html { render :new }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /artists/1
  # PATCH/PUT /artists/1.json
  def update
    respond_to do |format|
      if @artist.update(artist_params)
        format.html { redirect_to @artist, notice: 'Artist was successfully updated.' }
        format.json { render :show, status: :ok, location: @artist }
      else
        format.html { render :edit }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /artists/1
  # DELETE /artists/1.json
  def destroy
    @artist.destroy
    respond_to do |format|
      format.html { redirect_to artists_url, notice: 'Artist was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_artist
      @artist = Artist.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def artist_params
      params.require(:artist).permit(:artist_name, :genre)
    end
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/views/artists/_form.html.erb
<%= form_for(@artist) do |f| %>
  <% if @artist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@artist.errors.count, "error") %> prohibited this artist from being saved:</h2>

      <ul>
      <% @artist.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/artists/edit.html.erb
<h1>Editing Artist</h1>

<%= render 'form' %>

<%= link_to 'Show', @artist %> |
<%= link_to 'Back', artists_path %>

app/views/artists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Artists</h1>

<table>
  <thead>
    <tr>
      <th colspan="3">Artist Name:</th>
      <th>  </th>
      <th>Delete</th>
    </tr>
  </thead>

  <tbody>
    <% @artists.each do |artist| %>
      <tr>
        <td><%= link_to artist.artist_name, artist %></td>
        <td>  </td>
        <td><%= link_to '  ', artist, method: :delete, data: { confirm: 'Are you sure?' }, class: "glyphicon glyphicon-remove"%></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Artist', new_artist_path %>

app/views/artists/new.html.erb
<h1>New Artist</h1>

<form action="/artists" method="post">
Artist Name:<input type="text" name="artist[artist_name]">
<br>
Genre: <input type="text" name="artist[genre]">
<br>
<input type="submit" value="submit">
</form>

<%= link_to 'View all artists', artists_path %>

app/views/artists/show.html.erb
<p id="notice"><%= notice %></p>
<h1 class="header"><%= @artist.artist_name %></h1>
<h3 class="header">Genre: <%= @artist.genre %></h3>
<br>
<table>
	<th>
		<td>Albums</td>
	</th>
	<% @artist.albums.each do |album| %>
	<tr>
		<td></td>
		<td><%= link_to album.album_name, album_path(album.id) %></td>
	</tr>
<% end %>
</table>

<br>

<%= link_to 'Edit', edit_artist_path(@artist) %> |
<%= link_to 'Back', artists_path %>