config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: "users/registrations", sessions: "users/sessions" }
  root 'welcome#index'
  get '/users/:user_id/user_albums/data' => "user_albums#data"

  authenticate :user do
    resources :songs
    resources :albums
    resources :artists
    resources :user_albums
    get '/search' =>'search#index'
  end
end

#                   Prefix Verb   URI Pattern                                Controller#Action
#         new_user_session GET    /users/sign_in(.:format)                   users/sessions#new
#             user_session POST   /users/sign_in(.:format)                   users/sessions#create
#     destroy_user_session DELETE /users/sign_out(.:format)                  users/sessions#destroy
#            user_password POST   /users/password(.:format)                  devise/passwords#create
#        new_user_password GET    /users/password/new(.:format)              devise/passwords#new
#       edit_user_password GET    /users/password/edit(.:format)             devise/passwords#edit
#                          PATCH  /users/password(.:format)                  devise/passwords#update
#                          PUT    /users/password(.:format)                  devise/passwords#update
# cancel_user_registration GET    /users/cancel(.:format)                    users/registrations#cancel
#        user_registration POST   /users(.:format)                           users/registrations#create
#    new_user_registration GET    /users/sign_up(.:format)                   users/registrations#new
#   edit_user_registration GET    /users/edit(.:format)                      users/registrations#edit
#                          PATCH  /users(.:format)                           users/registrations#update
#                          PUT    /users(.:format)                           users/registrations#update
#                          DELETE /users(.:format)                           users/registrations#destroy
#                     root GET    /                                          welcome#index
#                          GET    /users/:user_id/user_albums/data(.:format) user_albums#data
#                    songs GET    /songs(.:format)                           songs#index
#                          POST   /songs(.:format)                           songs#create
#                 new_song GET    /songs/new(.:format)                       songs#new
#                edit_song GET    /songs/:id/edit(.:format)                  songs#edit
#                     song GET    /songs/:id(.:format)                       songs#show
#                          PATCH  /songs/:id(.:format)                       songs#update
#                          PUT    /songs/:id(.:format)                       songs#update
#                          DELETE /songs/:id(.:format)                       songs#destroy
#                   albums GET    /albums(.:format)                          albums#index
#                          POST   /albums(.:format)                          albums#create
#                new_album GET    /albums/new(.:format)                      albums#new
#               edit_album GET    /albums/:id/edit(.:format)                 albums#edit
#                    album GET    /albums/:id(.:format)                      albums#show
#                          PATCH  /albums/:id(.:format)                      albums#update
#                          PUT    /albums/:id(.:format)                      albums#update
#                          DELETE /albums/:id(.:format)                      albums#destroy
#                  artists GET    /artists(.:format)                         artists#index
#                          POST   /artists(.:format)                         artists#create
#               new_artist GET    /artists/new(.:format)                     artists#new
#              edit_artist GET    /artists/:id/edit(.:format)                artists#edit
#                   artist GET    /artists/:id(.:format)                     artists#show
#                          PATCH  /artists/:id(.:format)                     artists#update
#                          PUT    /artists/:id(.:format)                     artists#update
#                          DELETE /artists/:id(.:format)                     artists#destroy
#              user_albums GET    /user_albums(.:format)                     user_albums#index
#                          POST   /user_albums(.:format)                     user_albums#create
#           new_user_album GET    /user_albums/new(.:format)                 user_albums#new
#          edit_user_album GET    /user_albums/:id/edit(.:format)            user_albums#edit
#               user_album GET    /user_albums/:id(.:format)                 user_albums#show
#                          PATCH  /user_albums/:id(.:format)                 user_albums#update
#                          PUT    /user_albums/:id(.:format)                 user_albums#update
#                          DELETE /user_albums/:id(.:format)                 user_albums#destroy

app/models/album.rb
class Album < ActiveRecord::Base
	include PgSearch
	 pg_search_scope :search_by_name, 
                  :against => [:album_name],
                  :using => {
                    :tsearch => {:prefix => true}
                  }
	has_many :user_albums
  	has_many :users, through: :user_albums
	belongs_to :artist
	has_many :songs


	private
	def self.search(query) 
    	Album.search_by_name(query)
  	end
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :set_album, only: [:show, :edit, :update, :destroy]

  # GET /albums
  # GET /albums.json
  def index
    # binding.pry
    @albums = Album.all
  end

  # GET /albums/1
  # GET /albums/1.json
  def show
    @album = Album.find(params[:id])
    @song = Song.new
    respond_to do |format|
      format.html
      format.json{ render json: @album.songs }
    end
  end

  # GET /albums/new
  def new
    @album = Album.new
    @artists = Artist.all
  end

  # GET /albums/1/edit
  def edit
    @album = Album.find(params[:id])
    @artists = Artist.all
  end

  # POST /albums
  # POST /albums.json
  def create
    # binding.pry
    @album = Album.new(album_params)

    respond_to do |format|
      if @album.save
        format.html { redirect_to @album, notice: 'Album was successfully created.' }
        format.json { render :show, status: :created, location: @album }
      else
        format.html { render :new }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /albums/1
  # PATCH/PUT /albums/1.json
  def update
    respond_to do |format|
      if @album.update(album_params)
        format.html { redirect_to @album, notice: 'Album was successfully updated.' }
        format.json { render :show, status: :ok, location: @album }
      else
        format.html { render :edit }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /albums/1
  # DELETE /albums/1.json
  def destroy
    @album.destroy
    respond_to do |format|
      format.html { redirect_to albums_url, notice: 'Album was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_album
      @album = Album.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def album_params
      params.require(:album).permit(:album_name, :artist_id)
    end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/views/albums/_form.html.erb
<form method="post" action="/albums">
  <% if @album.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@album.errors.count, "error") %> prohibited this album from being saved:</h2>

      <ul>
      <% @album.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    Album Name:
      <input type="text" name="album[album_name]">
    Album Artist:
      <select name="album[artist_id]">
      <% @artists.each do |artist| %>
        <option value="<%= artist.id %>"><%= artist.artist_name %></option>
      <% end %>|
    </select>
    </div>
  <input type="submit" value="submit">
    
  </div>
</form>

app/views/albums/edit.html.erb
<h1>Editing Album</h1>

<%= render 'form' %>

<%= link_to 'Show', @album %> |
<%= link_to 'Back', albums_path %>

app/views/albums/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Albums</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @albums.each do |album| %>
    <tr>
      <th>Album</th>
      <th>Artist</th>
    </tr>
      <tr>
        <td><%= link_to album.album_name, album_path(album) %></td>
        <td><%= link_to album.artist.artist_name, artist_path(album.artist_id) %></td>
        <td><%= link_to 'Edit', edit_album_path(album), class: "btn btn-xs btn-primary"  %></td>
        <td><%= link_to 'Destroy', album, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-xs btn-danger"  %></td>
        <td><%= link_to 'Add To Favorites', edit_album_path(album), class: "btn btn-xs btn-primary"  %></td>  
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Album', new_album_path %>

app/views/albums/new.html.erb
<h1>New Album</h1>

<%= render 'form' %>


<%= link_to 'Cant find artist? Add new!', new_artist_path %>
<br>
<%= link_to 'View All Albums in Album Database', albums_path %>

app/views/albums/show.html.erb
<p id="notice"><%= notice %></p>

Album Name: <%= @album.album_name %>
<br>
Artist: <%= @album.artist.artist_name %>
<br>

Tracks:
<ol id="songlist"></ol>

Add New Song
<%= form_for @song, remote: true do |f| %>
	<%= hidden_field(:song, :album_id, :value => @album.id) %>
	<%= f.text_field :song_name %>
	<%= f.number_field :track_number %>
	<%= f.submit :submit %>
<% end %>
<!-- <form action="/songs.js" method="POST" data-remote="true" >
	<input type="text" placeholder="Song Name" name="song[song_name]">
	<input type="number" placeholder="Track Number" min="1" name="song[track_number]">
	<input type="hidden" value=<%= @album.id %> name="song[album_id]">
	<input type="submit" value="Add New">
</form> -->