config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: "users/registrations", sessions: "users/sessions" }
  root 'welcome#index'
  get '/users/:user_id/user_albums/data' => "user_albums#data"

  authenticate :user do
    resources :songs
    resources :albums
    resources :artists
    resources :user_albums
    get '/search' =>'search#index'
  end
end

#                   Prefix Verb   URI Pattern                                Controller#Action
#         new_user_session GET    /users/sign_in(.:format)                   users/sessions#new
#             user_session POST   /users/sign_in(.:format)                   users/sessions#create
#     destroy_user_session DELETE /users/sign_out(.:format)                  users/sessions#destroy
#            user_password POST   /users/password(.:format)                  devise/passwords#create
#        new_user_password GET    /users/password/new(.:format)              devise/passwords#new
#       edit_user_password GET    /users/password/edit(.:format)             devise/passwords#edit
#                          PATCH  /users/password(.:format)                  devise/passwords#update
#                          PUT    /users/password(.:format)                  devise/passwords#update
# cancel_user_registration GET    /users/cancel(.:format)                    users/registrations#cancel
#        user_registration POST   /users(.:format)                           users/registrations#create
#    new_user_registration GET    /users/sign_up(.:format)                   users/registrations#new
#   edit_user_registration GET    /users/edit(.:format)                      users/registrations#edit
#                          PATCH  /users(.:format)                           users/registrations#update
#                          PUT    /users(.:format)                           users/registrations#update
#                          DELETE /users(.:format)                           users/registrations#destroy
#                     root GET    /                                          welcome#index
#                          GET    /users/:user_id/user_albums/data(.:format) user_albums#data
#                    songs GET    /songs(.:format)                           songs#index
#                          POST   /songs(.:format)                           songs#create
#                 new_song GET    /songs/new(.:format)                       songs#new
#                edit_song GET    /songs/:id/edit(.:format)                  songs#edit
#                     song GET    /songs/:id(.:format)                       songs#show
#                          PATCH  /songs/:id(.:format)                       songs#update
#                          PUT    /songs/:id(.:format)                       songs#update
#                          DELETE /songs/:id(.:format)                       songs#destroy
#                   albums GET    /albums(.:format)                          albums#index
#                          POST   /albums(.:format)                          albums#create
#                new_album GET    /albums/new(.:format)                      albums#new
#               edit_album GET    /albums/:id/edit(.:format)                 albums#edit
#                    album GET    /albums/:id(.:format)                      albums#show
#                          PATCH  /albums/:id(.:format)                      albums#update
#                          PUT    /albums/:id(.:format)                      albums#update
#                          DELETE /albums/:id(.:format)                      albums#destroy
#                  artists GET    /artists(.:format)                         artists#index
#                          POST   /artists(.:format)                         artists#create
#               new_artist GET    /artists/new(.:format)                     artists#new
#              edit_artist GET    /artists/:id/edit(.:format)                artists#edit
#                   artist GET    /artists/:id(.:format)                     artists#show
#                          PATCH  /artists/:id(.:format)                     artists#update
#                          PUT    /artists/:id(.:format)                     artists#update
#                          DELETE /artists/:id(.:format)                     artists#destroy
#              user_albums GET    /user_albums(.:format)                     user_albums#index
#                          POST   /user_albums(.:format)                     user_albums#create
#           new_user_album GET    /user_albums/new(.:format)                 user_albums#new
#          edit_user_album GET    /user_albums/:id/edit(.:format)            user_albums#edit
#               user_album GET    /user_albums/:id(.:format)                 user_albums#show
#                          PATCH  /user_albums/:id(.:format)                 user_albums#update
#                          PUT    /user_albums/:id(.:format)                 user_albums#update
#                          DELETE /user_albums/:id(.:format)                 user_albums#destroy

app/models/user_album.rb
class UserAlbum < ActiveRecord::Base
	belongs_to :user
	belongs_to :album
	validates :user_id, presence: true
	validates :album_id, presence: true
	validates :user_id, :uniqueness => {:scope => [:album_id]}
end

app/controllers/user_albums_controller.rb
class UserAlbumsController < ApplicationController
	skip_before_filter :verify_authenticity_token
	before_action :set_user_album, only: [:destroy]
	before_action :get_user_id
	
	# index routes will show all albums in users collection and allow users to add new albums
	def index
		@useralbums = current_user.albums
		@albums = Album.all
		# @useralbum = UserAlbum.where
	end

	def create
		@user_album = UserAlbum.new(user_album_params)
		@user_album.user_id = get_user_id

		respond_to do |format|
			if @user_album.save
				format.html {redirect_ to @user_albums, "Saved Succesfully"}
				format.js
				format.json { render json: @user_album }
			end
			# should handle failed save
		end
	end

	# currently destroy is destroying records from the album table.... rather than user_albums
	def destroy
		# binding.pry
		@useralbum.destroy_all
		redirect_to user_albums_path
  	end

	private

	def set_user_album
		@useralbum = UserAlbum.where(album_id:params[:id],user_id:current_user.id)
	end

	def user_album_params
		params.require(:user_album).permit(:album_id, :user_id)
	end

	def get_user_id
		current_user.id
	end
end

app/helpers/user_albums_helper.rb
module UserAlbumsHelper
end

app/views/user_albums/_form.html.erb
<form  method="post" action="/user_albums" data-remote="true">
	<select name="user_album[album_id]">
		<% @albums.each do |album| %>
		<option value=<%= album.id %>><%= album.album_name %> by <%= album.artist.artist_name %></option>
		<% end %>
	</select>
	<input type="submit" value="submit">
</form>

app/views/user_albums/_user_album.html.erb
<tr>
	<td></td>
	<!-- album -->
	<td><%= link_to @user_album.album.album_name, album_path(@user_album.album.id) %></td>
	<!-- artist -->
	<td><%= link_to @user_album.album.artist.artist_name, artist_path(@user_album.album.artist.id) %></td>
	<!-- delete -->
	<td><%= link_to '', user_album_path(:id => @user_album.album.id), method: :delete, data: { confirm: 'Are you sure?' }, class: "glyphicon glyphicon-remove" %></td>
</tr>

app/views/user_albums/create.js.erb
$('.myalbums').append('<%= escape_javascript(render @user_album) %>');

app/views/user_albums/index.html.erb
<h1 class="header">My Album Collection</h1>

<table class="myalbums">
	<th>
		<td>Album</td>
		<td>Artist</td>
		<td>Delete</td>
	</th>
	<% @useralbums.each do |album| %>
		<!-- album name -->
	<tr>
		<td></td>
		<td>
			<%= link_to album.album_name, album_path(album.id) %>
		</td>
		<!-- album artist -->
		<td>
			<%= link_to album.artist.artist_name, artist_path(album.artist.id)%>
		</td>
		<!-- album delete button -->
		<td>
			<%= link_to '', user_album_path(:id => album.id), method: :delete, data: { confirm: 'Are you sure?' }, class: "glyphicon glyphicon-remove" %>
		</td>
	</tr>
	<% end %>	
</table>

<%= render 'form' %>
Cant find the album you are looking for?
<%= link_to 'Add a new album to our Album Database', new_album_path %>

app/views/user_albums/new.html.erb
<%= render 'form' %>
Can find the album you are looking for?
<%= link_to 'Add a new album to our Album Database', new_album_path %>